import { browser, by, element } from 'protractor';

/** Autogenerated AppPage class */
export class AppPage {
  /** Autogenerated navigateTo */
  navigateTo(): Promise<unknown> {
    return browser.get(browser.baseUrl) as Promise<unknown>;
  }

  /** Autogenerated getTitleText */
  getTitleText(): Promise<string> {
    return element(by.css('app-root .content span')).getText() as Promise<string>;
  }
}
